Description: >

  This template deploys a VPC, with a pair of public and private subnets spread
  across two Availabilty Zones. It deploys an Internet Gateway, with a default
  route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ),
  and default routes for them in the private subnets.

  It then deploys a highly available ECS cluster using an AutoScaling Group, with
  ECS hosts distributed across multiple Availability Zones.

  It also deploys a Jenkins instance used for building CI/CD pipelines.

Parameters:
  VpcTemplateUrl:
    Type: String
    Description: Signed url for vpc template stored in s3 bucket
  SgTemplateUrl:
    Type: String
    Description: Signed url for security-groups template stored in s3 bucket
  LbTemplateUrl:
    Type: String
    Description: Signed url for load-balancers template stored in s3 bucket
  EcsTemplateUrl:
    Type: String
    Description: Signed url for ecs-cluster template stored in s3 bucket
  LifecycleHookTemplateUrl:
    Type: String
    Description: Signed url for lifecyclehook template stored in s3 bucket
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VpcTemplateUrl
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.180.0.0/16
        PublicSubnet1CIDR: 10.180.8.0/21
        PublicSubnet2CIDR: 10.180.16.0/21
        PrivateSubnet1CIDR: 10.180.24.0/21
        PrivateSubnet2CIDR: 10.180.32.0/21

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SgTemplateUrl
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LbTemplateUrl
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
        Subnets: !GetAtt VPC.Outputs.PublicSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref EcsTemplateUrl
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: t2.large
        ClusterSize: 4
        VPC: !GetAtt VPC.Outputs.VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
        KeyName: !Ref KeyName

  LifecycleHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LifecycleHookTemplateUrl
      Parameters:
        Cluster: !GetAtt ECS.Outputs.Cluster
        ECSAutoScalingGroupName: !GetAtt ECS.Outputs.ECSAutoScalingGroupName


Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !GetAtt VPC.Outputs.VPC

  PublicSubnets:
    Description: A list of the public subnets
    Value: !GetAtt VPC.Outputs.PublicSubnets

  PrivateSubnets:
    Description: A list of the private subnets
    Value: !GetAtt VPC.Outputs.PrivateSubnets

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !GetAtt VPC.Outputs.PublicSubnet1

  PublicSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !GetAtt VPC.Outputs.PublicSubnet2

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !GetAtt VPC.Outputs.PrivateSubnet1

  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !GetAtt VPC.Outputs.PrivateSubnet2

  EcsListenerArn:
    Description: ECS ALB listener ARN
    Value: !GetAtt ALB.Outputs.Listener
  # ProductServiceUrl:
  #   Description: The URL endpoint for the product service
  #   Value: !Join ["/", [!GetAtt ALB.Outputs.LoadBalancerUrl, "products"]]
  #
  # WebsiteServiceUrl:
  #   Description: The URL endpoint for the website service
  #   Value: !Join ["", [!GetAtt ALB.Outputs.LoadBalancerUrl, "/"]]
